jsm-spring-boot-starter/src/main/java/cn/ibaijia/jsm/context/dao/model/OptLog.java
package cn.ibaijia.jsm.context.dao.model;

import cn.ibaijia.jsm.annotation.FieldAnn;
import cn.ibaijia.jsm.context.AppContext;
import cn.ibaijia.jsm.context.AppContextKey;
import cn.ibaijia.jsm.context.WebContext;
import cn.ibaijia.jsm.context.dao.BaseModel;

/**
 * @author zhili
 * createOn 2016年11月30日
 */
public class OptLog extends BaseModel {
    private static final long serialVersionUID = -969033916740549421L;
    @FieldAnn(required = false, maxLen = 50, comments = "服务ID")
    public String clusterId = AppContext.get(AppContextKey.CLUSTER_ID, "");
    @FieldAnn(required = false, comments = "应用名")
    public String appName = AppContext.get(AppContextKey.APP_NAME, "");
    @FieldAnn(required = false, comments = "环境")
    public String env = AppContext.get(AppContextKey.ENV, "");
    @FieldAnn(required = false, comments = "GIT_COMMIT_ID")
    public String gitHash = AppContext.get(AppContextKey.GIT_HASH, "");
    @FieldAnn(required = false, maxLen = 50, comments = "客户端ID")
    public String clientId;
    @FieldAnn(required = false, comments = "操作时间")
    public Long time;
    @FieldAnn(comments = "操作人ip")
    public String ip;
    @FieldAnn(comments = "操作请求ID")
    public String traceId;
    @FieldAnn(comments = "操作人MAC地址")
    public String mac;
    @FieldAnn(comments = "操作人用户ID")
    public String uid;
    @FieldAnn(comments = "模块名称")
    public String funcName;
    @FieldAnn(comments = "操作内容")
    public String optDesc;

    public OptLog() {

    }

    public OptLog(String ip, String mac, String uid, String funcName, String optDesc) {
        super();
        this.ip = ip;
        this.mac = mac;
        this.uid = uid;
        this.funcName = funcName;
        this.optDesc = optDesc;
        this.clientId = WebContext.getClientId();
    }
}

jsm-spring-boot-starter/src/main/java/cn/ibaijia/jsm/context/dao/model/Page.java
package cn.ibaijia.jsm.context.dao.model;

import cn.ibaijia.jsm.annotation.FieldAnn;
import cn.ibaijia.jsm.annotation.FieldType;
import cn.ibaijia.jsm.context.rest.validate.ValidateModel;
import cn.ibaijia.jsm.utils.LogUtil;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiParam;
import org.slf4j.Logger;

import java.util.List;
import java.util.Objects;


/**
 * desc 说明
 *
 * @param <T>
 * @author zhili
 * createOn 2016年11月30日
 */
public class Page<T> implements ValidateModel {
    private static Logger logger = LogUtil.log(Page.class);

    public Page() {
        super();
    }

    public Page(int pageSize) {
        super();
        this.pageSize = pageSize;
    }

    @ApiParam(hidden = true)
    @FieldAnn(required = false, comments = "当前页数据列表")
    public List<T> list;

    @FieldAnn(required = true, type = FieldType.NUMBER, comments = "当前页数", mockValue = "1")
    public int pageNo = 1;

    @FieldAnn(required = true, type = FieldType.NUMBER, comments = "每页条数", mockValue = "10")
    public int pageSize = 15;

    @ApiParam(hidden = true)
    @FieldAnn(required = false, comments = "总条数", mockValue = "10")
    public long totalCount = 0;

    @ApiParam(hidden = true)
    @JsonIgnore
    private String dbDialect = null;

    public List<T> getList() {
        return list;
    }

    public void setList(List<T> list) {
        this.list = list;
    }

    /**
     * 获取当前页号.
     */
    public int getPageNo() {
        return pageNo;
    }

    /**
     * 设置当前页号,序号从1开始,低于1时自动调整为1.
     */
    public void setPageNo(int pageNo) {
        this.pageNo = pageNo < 1 ? 1 : pageNo;
    }

    /**
     * 获取每页显示记录条数.
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * 设置每页的记录条数,低于2时自动调整为20.
     */
    public void setPageSize(int pageSize) {
        this.pageSize = pageSize < 1 ? 15 : pageSize;
    }

    /**
     * 获取总记录条数.
     */
    public long getTotalCount() {
        return totalCount;
    }

    /**
     * 设置总记录条数.
     */
    public void setTotalCount(long totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * 获取总页数(最后一页的页号).
     */
    public long getTotalPage() {
        if (totalCount <= 0) {
            return 1;
        } else {
            long count = totalCount / pageSize;
            if (totalCount % pageSize > 0) {
                count++;
            }
            return count;
        }
    }

    /**
     * 是否有上一页.
     */
    public boolean isHasPrevPage() {
        return (pageNo - 1 >= 1);
    }

    /**
     * 获取上一页的页号.
     */
    public int getPrevPage() {
        return isHasPrevPage() ? (pageNo - 1) : pageNo;
    }

    /**
     * 是否有下一页.
     */
    public boolean isHasNextPage() {
        return (pageNo + 1 <= getTotalPage());
    }

    /**
     * 获取下一页的页号.
     */
    public int getNextPage() {
        return isHasNextPage() ? (pageNo + 1) : pageNo;
    }

    /**
     * 获取当前页面上第一条记录对应数据库中的索引.
     */
    public int getBeginIndex() {
        return (pageNo - 1) * pageSize;
    }

    public String getDbDialect() {
        return dbDialect;
    }

    public void setDbDialect(String dbDialect) {
        this.dbDialect = dbDialect;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Page<?> page = (Page<?>) o;
        return pageNo == page.pageNo &&
                pageSize == page.pageSize &&
                totalCount == page.totalCount;
    }

    @Override
    public int hashCode() {

        return Objects.hash(pageNo, pageSize, totalCount);
    }
}

jsm-spring-boot-starter/src/main/java/cn/ibaijia/jsm/context/rest/resp/vo/ExcelVo.java
package cn.ibaijia.jsm.context.rest.resp.vo;

import cn.ibaijia.jsm.annotation.FieldAnn;
import cn.ibaijia.jsm.context.rest.resp.OutputVo;
import cn.ibaijia.jsm.context.rest.validate.ValidateModel;
import com.alibaba.fastjson.annotation.JSONField;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiParam;
import org.apache.poi.ss.usermodel.Workbook;

/**
 * @Author: LongZL
 * @Date: 2022/6/2 18:36
 */
public class ExcelVo implements ValidateModel, OutputVo {

    @FieldAnn(comments = "文件名")
    public String fileName = "unknown_file_name.xls";

    @JSONField(serialize = false)
    @JsonIgnore
    @ApiParam(hidden = true)
    @FieldAnn(comments = "Workbook")
    public Workbook workbook;

    public ExcelVo() {
    }

    public ExcelVo(Workbook workbook) {
        this.workbook = workbook;
    }

    public ExcelVo(String fileName, Workbook workbook) {
        this.fileName = fileName;
        this.workbook = workbook;
    }
}

jsm-spring-boot-starter/src/main/java/cn/ibaijia/jsm/context/rest/resp/vo/FileVo.java
package cn.ibaijia.jsm.context.rest.resp.vo;

import cn.ibaijia.jsm.annotation.FieldAnn;
import cn.ibaijia.jsm.context.rest.resp.OutputVo;
import cn.ibaijia.jsm.context.rest.validate.ValidateModel;
import com.alibaba.fastjson.annotation.JSONField;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiParam;
import org.apache.http.Header;

import java.util.List;

/**
 * @Author: LongZL
 * @Date: 2022/6/2 18:36
 */
public class FileVo implements ValidateModel, OutputVo {

    @FieldAnn(comments = "自定义headers")
    public List<Header> headers;

    @FieldAnn(comments = "文件名")
    public String fileName = "unknown_file_name.jpg";

    @JSONField(serialize = false)
    @JsonIgnore
    @ApiParam(hidden = true)
    @FieldAnn(comments = "输出流对象,String,InputStream,File,Object.")
    public Object content;

    public FileVo() {
    }

    public FileVo(Object content) {
        this.content = content;
    }

    public FileVo(String fileName, Object content) {
        this.fileName = fileName;
        this.content = content;
    }

    public FileVo(List<Header> headers, String fileName, Object content) {
        this.headers = headers;
        this.fileName = fileName;
        this.content = content;
    }
}

jsm-spring-boot-starter/src/main/java/cn/ibaijia/jsm/context/rest/resp/vo/FollowVo.java
package cn.ibaijia.jsm.context.rest.resp.vo;

import cn.ibaijia.jsm.annotation.FieldAnn;
import cn.ibaijia.jsm.context.rest.resp.OutputVo;
import cn.ibaijia.jsm.context.rest.validate.ValidateModel;

/**
 * @Author: LongZL
 * @Date: 2022/6/2 18:36
 */
public class FollowVo implements ValidateModel, OutputVo {

    @FieldAnn(comments = "")
    public String uri;

    public FollowVo() {
    }

    public FollowVo(String uri) {
        this.uri = uri;
    }
}

jsm-spring-boot-starter/src/main/java/cn/ibaijia/jsm/context/rest/resp/vo/HtmlVo.java
package cn.ibaijia.jsm.context.rest.resp.vo;

import cn.ibaijia.jsm.annotation.FieldAnn;
import cn.ibaijia.jsm.context.rest.resp.OutputVo;
import cn.ibaijia.jsm.context.rest.validate.ValidateModel;

/**
 * @Author: LongZL
 * @Date: 2022/6/2 18:36
 */
public class HtmlVo implements ValidateModel, OutputVo {

    @FieldAnn(comments = "")
    public String content;

    public HtmlVo() {
    }

    public HtmlVo(String content) {
        this.content = content;
    }
}

jsm-spring-boot-starter/src/main/java/cn/ibaijia/jsm/gen/model/ApiInfo.java
package cn.ibaijia.jsm.gen.model;

import cn.ibaijia.jsm.consts.BaseConstants;
import cn.ibaijia.jsm.gen.GenUtil;
import cn.ibaijia.jsm.utils.ReflectionUtil;

import java.io.Serializable;
import java.util.List;

/**
 * @author longzl
 */
public class ApiInfo implements Serializable {
    private static final long serialVersionUID = 1L;
    public String name;
    public String httpMethod;
    public String url;
    public List<FieldInfo> pathVarList;
    public List<FieldInfo> reqParamList;
    public List<FieldInfo> bodyParamList;
    public List<FieldInfo> respParamList;
    public String comments;

    public boolean pathVarListShow = true;
    public boolean reqParamListShow = true;
    public boolean bodyParamListShow = true;
    public boolean respParamListShow = true;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getHttpMethod() {
        return httpMethod;
    }

    public void setHttpMethod(String httpMethod) {
        this.httpMethod = httpMethod;
    }

    public String getUrl() {
        return url;
    }

    public String getFrontUrl() {
        if (url.contains("{")) {
            return url.replace("{", "${");
        }
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public List<FieldInfo> getPathVarList() {
        return pathVarList;
    }

    public void setPathVarList(List<FieldInfo> pathVarList) {
        this.pathVarList = pathVarList;
    }

    public List<FieldInfo> getReqParamList() {
        return reqParamList;
    }

    public void setReqParamList(List<FieldInfo> reqParamList) {
        this.reqParamList = reqParamList;
    }

    public List<FieldInfo> getBodyParamList() {
        return bodyParamList;
    }

    public void setBodyParamList(List<FieldInfo> bodyParamList) {
        this.bodyParamList = bodyParamList;
    }

    public List<FieldInfo> getRespParamList() {
        return respParamList;
    }

    public void setRespParamList(List<FieldInfo> respParamList) {
        this.respParamList = respParamList;
    }

    public String getTsReqVar() {
        StringBuilder sb = new StringBuilder();
        if (this.pathVarList != null) {
            for (FieldInfo fieldInfo : this.pathVarList) {
                sb.append(sb.length() > 0 ? BaseConstants.SYSTEM_SYMBOL_COMMA : BaseConstants.SYSTEM_EMPTY_STRING)
                        .append(fieldInfo.fieldName).append(": ").append(fieldInfo.getTsFieldType());
            }
        }
        if (this.reqParamList != null) {
            if (GenUtil.existsNonFileReqParam(this.reqParamList)) {
                sb.append(sb.length() > 0 ? BaseConstants.SYSTEM_SYMBOL_COMMA : BaseConstants.SYSTEM_EMPTY_STRING)
                        .append("reqParams: model.").append(GenUtil.getReqParamTsTypeName(this.name));
            }
            //文件上传
            for (FieldInfo fieldInfo : this.reqParamList) {
                if (ReflectionUtil.isMultipartFile(fieldInfo.fieldType) || ReflectionUtil.isMultipartFileArray(fieldInfo.fieldType)) {
                    sb.append(sb.length() > 0 ? BaseConstants.SYSTEM_SYMBOL_COMMA : BaseConstants.SYSTEM_EMPTY_STRING)
                            .append(fieldInfo.fieldName).append(": ").append(BaseConstants.SYSTEM_STRING_FILE);
                }
                if (ReflectionUtil.isMultipartFileArray(fieldInfo.fieldType)) {
                    sb.append(sb.length() > 0 ? BaseConstants.SYSTEM_SYMBOL_COMMA : BaseConstants.SYSTEM_EMPTY_STRING)
                            .append(BaseConstants.SYSTEM_SYMBOL_ARRAY);
                }
            }
        }
        if (this.bodyParamList != null) {
            sb.append(sb.length() > 0 ? "," : "").append("reqBody: model.").append(GenUtil.getReqBodyTsTypeName(this.name));
            return sb.toString();
        }
        return sb.toString();
    }

    public String getJsReqVar() {
        StringBuilder sb = new StringBuilder();
        if (this.pathVarList != null) {
            for (FieldInfo fieldInfo : this.pathVarList) {
                sb.append(sb.length() > 0 ? BaseConstants.SYSTEM_SYMBOL_COMMA : BaseConstants.SYSTEM_EMPTY_STRING)
                        .append(fieldInfo.fieldName);
            }
        }
        if (this.reqParamList != null) {
            if (GenUtil.existsNonFileReqParam(this.reqParamList)) {
                sb.append(sb.length() > 0 ? BaseConstants.SYSTEM_SYMBOL_COMMA : BaseConstants.SYSTEM_EMPTY_STRING)
                        .append("reqParams");
            }
            //文件上传
            for (FieldInfo fieldInfo : this.reqParamList) {
                if (ReflectionUtil.isMultipartFile(fieldInfo.fieldType) || ReflectionUtil.isMultipartFileArray(fieldInfo.fieldType)) {
                    sb.append(sb.length() > 0 ? BaseConstants.SYSTEM_SYMBOL_COMMA : BaseConstants.SYSTEM_EMPTY_STRING)
                            .append(fieldInfo.fieldName);
                }
            }
        }
        if (this.bodyParamList != null) {
            sb.append(sb.length() > 0 ? "," : "").append("reqBody");
            return sb.toString();
        }
        return sb.toString();
    }

    public String getFrontReqVarName() {
        StringBuilder sb = new StringBuilder();
        if (this.reqParamList != null) {
            if (GenUtil.existsNonFileReqParam(this.reqParamList)) {
                sb.append(" + parseQueryString(reqParams)");
            }
            //文件上传
            for (FieldInfo fieldInfo : this.reqParamList) {
                if (ReflectionUtil.isMultipartFile(fieldInfo.fieldType) || ReflectionUtil.isMultipartFileArray(fieldInfo.fieldType)) {
                    sb.append(", ").append(fieldInfo.fieldName);
                }
            }
        }
        if (this.bodyParamList != null) {
            sb.append(", reqBody");
        }
        return sb.toString();
    }

    public String getTsReqParamType() {
        if (this.reqParamList != null) {
            return GenUtil.getReqParamTsTypeName(this.name);
        }
        return null;
    }

    public String getTsReqBodyType() {
        if (this.bodyParamList != null) {
            return GenUtil.getReqBodyTsTypeName(this.name);
        }
        return null;
    }

    public String getTsRespBodyType() {
        if (this.respParamList != null) {
            return GenUtil.getRespBodyTsTypeName(this.name);
        }
        return null;
    }


}

jsm-spring-boot-starter/src/main/java/cn/ibaijia/jsm/gen/model/FieldInfo.java
package cn.ibaijia.jsm.gen.model;

import cn.ibaijia.jsm.annotation.DicAnn;
import cn.ibaijia.jsm.annotation.FieldAnn;
import cn.ibaijia.jsm.gen.GenUtil;

import java.io.Serializable;
import java.util.List;

/**
 * @author longzl
 */
public class FieldInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    public String fieldName;
    public String fieldType;
    public String defaultVal;
    public String comments;
    public Boolean required = false;
    public Integer maxLength = 250;

    /**
     * 非普通对象 和 map可预见的字段对象
     */
    public List<FieldInfo> fieldInfoList;
    /**
     * 所处对象的层级 0 开始
     */
    public int level;
    /**
     * 字段的 注解
     */
    public FieldAnn fieldAnn;
    /**
     * 字段的 字典 注解
     */
    public DicAnn dicAnn;

    public boolean show = true;

    public String getFieldName() {
        return fieldName;
    }

    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    public String getFieldType() {
        return fieldType;
    }

    public void setFieldType(String fieldType) {
        this.fieldType = fieldType;
    }

    public String getDefaultVal() {
        return defaultVal;
    }

    public void setDefaultVal(String defaultVal) {
        this.defaultVal = defaultVal;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public Boolean getRequired() {
        return required;
    }

    public void setRequired(Boolean required) {
        this.required = required;
    }

    public Integer getMaxLength() {
        return maxLength;
    }

    public void setMaxLength(Integer maxLength) {
        this.maxLength = maxLength;
    }
    public String getTsFieldType() {
        return GenUtil.getTsFieldType(this.fieldType, this.dicAnn);
    }

    public List<FieldInfo> getFieldInfoList() {
        return fieldInfoList;
    }
}

jsm-spring-boot-starter/src/main/resources/META-INF/ftl/frontJsApi.ftl
<#setting number_format="#"/>
import ${req.ajaxLibName} from "${req.ajaxLibPath}"
const baseUrl = ${req.baseUri?contains('.')?string('','"')}${req.baseUri}${req.baseUri?contains('.')?string('','"')}

const parseQueryString = (params) => {
    let queryString = ''
    Object.keys(params).forEach((key) => {
        if (params[key] != undefined && params[key] != null) {
            queryString += (queryString ? "&" : "?")
            queryString += ${r'`${encodeURIComponent(key)}=${encodeURIComponent(params[key])}`'}
        }
    })
    return queryString
}

<#list controllerInfo.apiInfos as apiInfo>
/**
 * @description ${apiInfo.comments}
 <#if apiInfo.pathVarList??>
 * @Path参数
 <#list apiInfo.pathVarList as field>
 * @param ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 </#list>
 </#if>
 <#if apiInfo.reqParamList??>
 * @请求参数
 <#list apiInfo.reqParamList as field>
 * @param ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 </#list>
 </#if>
 <#if apiInfo.bodyParamList??>
 * @请求Body
 <#list apiInfo.bodyParamList as field>
 * @param ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 <#if field.fieldInfoList??>
 <#list field.fieldInfoList as field>
 * @param  ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 <#if field.fieldInfoList??>
 <#list field.fieldInfoList as field>
 * @param   ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 <#if field.fieldInfoList??>
 <#list field.fieldInfoList as field>
 * @param    ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 </#list>
 </#if>
 </#list>
 </#if>
 </#list>
 </#if>
 </#list>
 </#if>
 <#if apiInfo.respParamList??>
 * @响应Body
 <#list apiInfo.respParamList as field>
 * @param ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 <#if field.fieldInfoList??>
 <#list field.fieldInfoList as field>
 * @param  ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 <#if field.fieldInfoList??>
 <#list field.fieldInfoList as field>
 * @param   ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 <#if field.fieldInfoList??>
 <#list field.fieldInfoList as field>
 * @param    ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 </#list>
 </#if>
 </#list>
 </#if>
 </#list>
 </#if>
 </#list>
 </#if>
 */
export const ${apiInfo.name} = (${apiInfo.jsReqVar?default("")}) => {
    return ${req.ajaxLibName}.${apiInfo.httpMethod}(`${r'${baseUrl}'}${apiInfo.frontUrl}`${apiInfo.frontReqVarName?default("")})
}
</#list>

export default {
<#list controllerInfo.apiInfos as apiInfo>
    ${apiInfo.name},
</#list>
}

jsm-spring-boot-starter/src/main/resources/META-INF/ftl/frontTsApi.ftl
<#setting number_format="#"/>
import ${req.ajaxLibName} from "${req.ajaxLibPath}"
import * as model from "${req.apiModelDir?starts_with('.')?string('','./')}${req.apiModelDir}/${req.apiName}Model"
const baseUrl = ${req.baseUri?contains('.')?string('','"')}${req.baseUri}${req.baseUri?contains('.')?string('','"')}

const parseQueryString = (params: any) => {
    let queryString = ''
    Object.keys(params).forEach((key) => {
        if (params[key] != undefined && params[key] != null) {
            queryString += (queryString ? "&" : "?")
            queryString += ${r'`${encodeURIComponent(key)}=${encodeURIComponent(params[key])}`'}
        }
    })
    return queryString
}

<#list controllerInfo.apiInfos as apiInfo>
/**
 * @description ${apiInfo.comments}
 <#if apiInfo.pathVarList??>
 * @Path参数
 <#list apiInfo.pathVarList as field>
 * @param ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 </#list>
 </#if>
 <#if apiInfo.reqParamList??>
 * @请求参数 ${req.apiName}Model.${apiInfo.tsReqParamType?default("")}
 <#list apiInfo.reqParamList as field>
 * @param ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 </#list>
 </#if>
 <#if apiInfo.bodyParamList??>
 * @请求Body
 <#list apiInfo.bodyParamList as field>
 * @param ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 <#if field.fieldInfoList??>
 <#list field.fieldInfoList as field>
 * @param  ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 <#if field.fieldInfoList??>
 <#list field.fieldInfoList as field>
 * @param   ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 <#if field.fieldInfoList??>
 <#list field.fieldInfoList as field>
 * @param    ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 </#list>
 </#if>
 </#list>
 </#if>
 </#list>
 </#if>
 </#list>
 </#if>
 <#if apiInfo.respParamList??>
 * @响应Body
 <#list apiInfo.respParamList as field>
 * @param ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 <#if field.fieldInfoList??>
 <#list field.fieldInfoList as field>
 * @param  ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 <#if field.fieldInfoList??>
 <#list field.fieldInfoList as field>
 * @param   ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 <#if field.fieldInfoList??>
 <#list field.fieldInfoList as field>
 * @param    ${field.fieldName},${field.fieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 </#list>
 </#if>
 </#list>
 </#if>
 </#list>
 </#if>
 </#list>
 </#if>
 * @return ${req.apiName}Model.${apiInfo.tsRespBodyType?default("")}
 */
export const ${apiInfo.name} = (${apiInfo.tsReqVar?default("")}) => {
    return ${req.ajaxLibName}.${apiInfo.httpMethod}(`${r'${baseUrl}'}${apiInfo.frontUrl}`${apiInfo.frontReqVarName?default("")})
}
</#list>

export default {
<#list controllerInfo.apiInfos as apiInfo>
    ${apiInfo.name},
</#list>
}

jsm-spring-boot-starter/src/main/resources/META-INF/ftl/frontTsModel.ftl
<#setting number_format="#"/>
<#if tsTypeInfoList??>
    <#list tsTypeInfoList as item>
        <#if item.fieldInfoList??>
/**
 * @description ${item.typeName}
 <#list item.fieldInfoList as field>
 * @param ${field.fieldName},${field.tsFieldType},${field.required?string('是', '否')},${field.comments?default("")},${field.defaultVal?default("")}
 </#list>
 */
export type ${item.typeName} = {
 <#list item.fieldInfoList as field>
    ${field.fieldName}${field.required?string('', '?')}: ${field.tsFieldType}
 </#list>
}
    </#if>
    <#if item.arrayElementName??>
/**
 * @description ${item.arrayElementName}数组
 */
export type ${item.typeName} = ${item.arrayElementName}[]
    </#if>
</#list>
</#if>